#Numpy: 
It is a general puppose array processing package. It provides a high performance multi dimentional array object, and tool for working with these arrays. It is the fundamental pacakge for scientific computing with python

What is array
An array is data structure that stores values of same data type

In [ ]:
#pip install numpy
# conda install numpy

In [ ]:
## initially lets import numpy
import numpy as np

In [ ]:
l=[1,2,3,4,5]
a=np.array(l)
type(a)
print(a)

# to check the shape f array
print(a.shape) # specifies no of rows and columns: if 1 dimenentional-species the no. of elements

[1 2 3 4 5]
(5,)


In [ ]:
#multi dimentioal array

l1=[1,2,7,4,0]
l2=[1,6,3,5,5]
l3=[4,2,3,4,5]

a1=np.array([l1,l2,l3])
print(a1)  # 2 dimentional array:2 [] barckets
print(a1.shape)

a1.reshape(1,15)
print(a1)
print(a1.shape) 

[[1 2 7 4 0]
 [1 6 3 5 5]
 [4 2 3 4 5]]
(3, 5)
[[1 2 7 4 0]
 [1 6 3 5 5]
 [4 2 3 4 5]]
(3, 5)


In [ ]:
# Indexing

## Accessing the array elements
# 1 dementional array
a=np.array([1,2,3,4,5,6,7,8])
print(a[3])

print(a1[:,:])
print(a1[:2,: 3])
print(a1[:3,: 3])
print(a1[:2,: 2])
print(a1[:2,2:4])

4
[[1 2 7 4 0]
 [1 6 3 5 5]
 [4 2 3 4 5]]
[[1 2 7]
 [1 6 3]]
[[1 2 7]
 [1 6 3]
 [4 2 3]]
[[1 2]
 [1 6]]
[[7 4]
 [3 5]]


In [ ]:
# inbuilt functions

#arrange
a=np.arange(0,10)  # between 0-10 all the elements will be displayed
print(a)
a=np.arange(0,10, step=2)
print(a)

# line space
np.linspace(1,10,50) #  50 equi spaced values between 1-10

#braodcasting
a[3:]=100
print(a)
a1=a
a1[3:]=200
print(a1)
print(a)

#Copy function and braodcasting

a2=a.copy()
a2[3:]=500
print(a2)
print(a)

# ones
print(np.ones(4))
print(np.ones(4, dtype=int))
print(np.ones((2,5),dtype=int))





[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[  0   2   4 100 100]
[  0   2   4 200 200]
[  0   2   4 200 200]
[  0   2   4 500 500]
[  0   2   4 200 200]
[1. 1. 1. 1.]
[1 1 1 1]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[-1.53609352,  2.81078184,  1.91400003],
       [-0.34654649,  0.40723834,  0.12785635],
       [-1.59196841, -2.04956823, -0.15570249]])

In [ ]:
# conditions useful in exploratory data analysis
a=np.array([1,2,3,4,5,6,7,8])
val=5
print(a<val)
print(a[a<val])

print(a*2)
print(a/2)
print(a%2)
print(a**2)

[ True  True  True  True False False False False]
[1 2 3 4]
[ 2  4  6  8 10 12 14 16]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[1 0 1 0 1 0 1 0]
[ 1  4  9 16 25 36 49 64]


In [ ]:
# random distribution
np.random.rand(3,3)
np.random.randn(3,3)
np.random.randint(0,100,8).reshape(2,4)
np.random.random_sample((1,5))

array([[0.35609981, 0.99994329, 0.31940261, 0.12926073, 0.02054155]])

#Pandas



In [ ]:
import pandas as pd

In [ ]:
#ceating data frame


df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'], columns=['column1','column2','column3','column4'])
df.head()


column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [ ]:
df.to_csv('Test1.csv')

In [ ]:
#accesing the elements: 
#1) .loc : will be focusing on row index
#2)  .iloc: will be focusing on both row index and column index
df.loc['Row1']
type(df.loc['Row1'])  # data series: can be either 1 row or 1 clumn: data frame: more than 1 row or 1 column

df.iloc[:,:]
df.iloc[0:2,0:2]
df['column2']
df[['column2','column3']]

column2  column3
Row1        1        2
Row2        5        6
Row3        9       10
Row4       13       14
Row5       17       18

In [ ]:
#convert dataframes into array: 
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
df['column1'].value_counts()
df.shape
df['column1'].value_counts().shape

(5,)

In [ ]:
df.isnull()
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [ ]:
df['column1'].unique()

array([ 0,  4,  8, 12, 16])